name: run unit tests
on:
  pull_request:
    # types: [ labeled ]

jobs:
  analyze:
    # if: "contains(toJson(github), 'Test') || github.event.release || github.event.release.prerelease"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: 'Analyze'
        run: flutter pub get && flutter analyze .

      - name: 'Format'
        run: flutter format lib/** -l 100 --fix --set-exit-if-changed

      - name: 'Run tests'
        run: flutter test -r expanded